name: CI for code linting

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      -
        name: Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
